/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author samuel
 */
public class login extends javax.swing.JFrame {

public Connection cn;
public Statement st;
   
   
    public login() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        try
        {
        Class.forName("com.mysql.jdbc.Driver");
        cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/bs_alm","root","");
        st=cn.createStatement();
         
        }
        catch(Exception e)
                {
                
                
                
                }
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo_personas = new javax.swing.JLabel();
        login_usuario = new javax.swing.JLabel();
        login_contra = new javax.swing.JLabel();
        get_contra = new javax.swing.JPasswordField();
        get_usu = new javax.swing.JTextField();
        login_ingresar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        fondo_cartel = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        fondo_celeste = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo_personas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/295128.png"))); // NOI18N
        fondo_personas.setText("jLabel2");
        getContentPane().add(fondo_personas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 20, 410, 360));

        login_usuario.setText("Usuario :");
        getContentPane().add(login_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        login_contra.setText("Contraseña :");
        getContentPane().add(login_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));
        getContentPane().add(get_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 110, -1));
        getContentPane().add(get_usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 110, -1));

        login_ingresar.setText("Ingresar");
        login_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(login_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        jButton1.setText("Crear Usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        fondo_cartel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plantilla-de-login-sobre-un-fondo-azul_1017-6722.png"))); // NOI18N
        fondo_cartel.setText("jLabel1");
        getContentPane().add(fondo_cartel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 280, 350));

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        fondo_celeste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/celeste_gradient_verde_claro_.jpg"))); // NOI18N
        fondo_celeste.setText("jLabel1");
        getContentPane().add(fondo_celeste, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void login_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_ingresarActionPerformed

     try{
        String sql;
       String t = null;
       sql= "Select cargo from seguridad where user = '"+ get_usu.getText()+"'and  password = '"+String.valueOf(get_contra.getPassword())+"'";
        ResultSet rss= st.executeQuery(sql);   
        if(rss.next())
        {
         switch(rss.getString("cargo"))
                 {
                     case "admin":
                         JOptionPane.showMessageDialog(null, "BIENVENIDO ADMINISTRADOR");
                     ventana_admin b = new ventana_admin();
                     b.setVisible(true);
                     this.dispose(); 
                     break;
                     
                     case "empleado":
                         JOptionPane.showMessageDialog(null, "BIENVENIDO ");
                     ventana_emple a = new ventana_emple();
                      a.setVisible(true);
                    this.dispose(); 
                     break;
                 
                 }
      
        }else
        {
        JOptionPane.showMessageDialog(null,"Usuario o contraseña no validos");
        }
        
     }
     catch(Exception e)
             {
             
             JOptionPane.showMessageDialog(null,"Usuario o contraseña no validos");
             
             }
    }//GEN-LAST:event_login_ingresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        Crear_usuario p = new Crear_usuario();
        p.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JLabel fondo_cartel;
    private javax.swing.JLabel fondo_celeste;
    private javax.swing.JLabel fondo_personas;
    private javax.swing.JPasswordField get_contra;
    private javax.swing.JTextField get_usu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel login_contra;
    private javax.swing.JButton login_ingresar;
    private javax.swing.JLabel login_usuario;
    // End of variables declaration//GEN-END:variables
}
